### ISSUE TITLE
Progress color always matching Normal color

### ISSUE THREAD

**Issue by pakoito** [dmytrodanylyk/android-process-button#33]
This is my button

        <com.dd.processbutton.iml.ActionProcessButton
            pb:pb_colorPressed="@android:color/transparent"
            pb:pb_colorComplete="@color/blue"
            pb:pb_textComplete="@string/complete"
            pb:pb_colorError="@color/red"
            pb:pb_textError="@string/error"
            pb:pb_colorProgress="@color/blue"
            pb:pb_textProgress="@string/progress"
            pb:pb_colorNormal="@color/green"
            android:text="@string/confirm_idle" />

the progress state shows as green for some reason. I'm not setting the colors again in code or anything.

**Comment by dmytrodanylyk** [comment]
Try to run [sample](https://github.com/dmytrodanylyk/android-process-button/tree/master/sample) app and check if issues remains.

**Comment by pakoito** [comment]
The issue is in the sample app too: http://imgur.com/a/tlAtW

**Comment by dmytrodanylyk** [comment]
@pakoito sorry, I can't reproduce this issue. For me color always changes according to `pb_colorProgress`. Can you provide Android Version and Device manufacturer?

**Comment by pakoito** [comment]
Samsung Galaxy S4, Android 4.4.2

**Comment by dmytrodanylyk** [comment]
I just tried on Android 4.4.4 device, all seems to work. Can you install sample app from [play store](https://play.google.com/store/apps/details?id=com.dd.sample.progressbutton&hl=en)? Also can you check on emulator or another device?

**Comment by pakoito** [comment]
Xiaomi MI2-S with MIUI 6 (4.1.X) with the app from the store has the same issue.

**Comment by dmytrodanylyk** [comment]
I have tested on several devices, Nexus 5, Nexus 7, Xperia S and Genymotion. So when you install sample app, and choose Action Button Progress sample, progress is green?

**Comment by dmytrodanylyk** [comment]
[Link to video](https://www.dropbox.com/s/2f0ttnz3ul2hmqk/2015-03-07-14-25-30_screenRecording.mp4?dl=0) :)

**Comment by pakoito** [comment]
Your video is showing the problem too! Check the imgur link above, progress state -which if I understood correctly is Loading.. - is set to white background, yet the button still shows the same as idle. My original post has Loading green.

In the default sample idle is blue and loading is violet or purple, IIRC. If my color blindness is not kicking in, your video shows both as the same color.

**Comment by dmytrodanylyk** [comment]
Ok, I misunderstood you. So `pb_colorProgress` is used for button progress line, in `btnSignIn.setMode(ActionProcessButton.Mode.PROGRESS);` mode. So you can't change color of button in progress mode.

**Comment by pakoito** [comment]
Okay, can you please put this as a feature request then, please?

**Comment by dmytrodanylyk** [comment]
@pakoito yes, but I will not be able to update library for a while...

**Comment by dmytrodanylyk** [comment]
Created issue #35

**Comment by pakoito** [comment]
Great, thank you.
