### ISSUE TITLE
mNormalText

### ISSUE THREAD

**Issue by jjhesk** [dmytrodanylyk/android-process-button#37]
There is bug when press the button the button will show up the processing text and until in some situation i need to manually change the state to normal and the Normal Text does not come back up instead it shows the default text that is defined in the xml. Are there a better way to show do the setNormalText that will able to be programmed dynamically from manually changes?

**Comment by nirvik66** [comment]
I'm also having the same problem.

**Comment by dmytrodanylyk** [comment]
Thanks for contribution. New version uploaded to Maven Central, should be available soon:

```
compile 'com.github.dmytrodanylyk.android-process-button:library:1.0.4'
```
