### ISSUE TITLE
README

### ISSUE THREAD

**Issue by IgorGanapolsky** [dmytrodanylyk/android-process-button#39]
Hello,
why does your README say:
`compile 'com.github.dmytrodanylyk.android-process-button:library:1.0.3`
but your release says:
`compile 'com.github.dmytrodanylyk.android-process-button:library:0.0.7`

Igor

**Comment by dmytrodanylyk** [comment]
Where you found `compile 'com.github.dmytrodanylyk.android-process-button:library:0.0.7` ?

**Comment by IgorGanapolsky** [comment]
Look at the 'releases' on github repo.

**Comment by dmytrodanylyk** [comment]
Completely forgot about this :)
