### ISSUE TITLE
Question: re-enable button after tot secs

### ISSUE THREAD

**Issue by brunano21** [dmytrodanylyk/android-process-button#48]
I'm in the situation where I do a http request. If I get an error, I set the progress value to -1 showing the error button. 
However, I would like to know how it's possible re enable the button (progress = 0) after a certain amount of seconds.
Does the library provide this mechanism? If not, what could you suggest?
Thanks!!

**Comment by dmytrodanylyk** [comment]
Create [Handler](http://developer.android.com/reference/android/os/Handler.html) object and call `postDelay` method to change button state to initial, after certain amount of time.

**Comment by brunano21** [comment]
Oh right. Thanks!
