### ISSUE TITLE
Owner, where are you?

### ISSUE THREAD

**Issue by rockstardev** [dmytrodanylyk/android-process-button#57]
Hey @dmytrodanylyk - do you need help with this repo? There are bunch of good pull requests waiting and I would prefer some of them are merged to fix bugs and have unified base version.

Let me know if you need help with administration.

**Comment by dmytrodanylyk** [comment]
Hi, unfortunately I am don't have time to further support this repo. If you want you can clone it and do some fixes / improvements.

If you do so, let me know, I could put link to your version in `README.md` file.

**Comment by rockstardev** [comment]
@dmytrodanylyk It's funny that it also took me so much to respond ;)

I've done some changes to streamline usage of button (theme + gradle). I've submitted pull request:
https://github.com/dmytrodanylyk/android-process-button/pull/58

Instead of linking my repo I would prefer that you add me as contributor to yours... that way I can take care of some pull requests + see if there is anything other contributors want to fix.
